### ISSUE TITLE
Running in real time 

### ISSUE THREAD

**Issue by Boukhechba** [Chang-Chia-Chi/TrackNet-Badminton-Tracking-tensorflow2#5]
Was anyone able to run this in real time ?. The current FPS rate for me is too low.

**Comment by StanRuessink** [comment]
I have the same issue, have you found an answer yet?

**Comment by Q2Learn** [comment]
What's your current FPS? I am getting like 0.2 FPS :/

**Comment by Chang-Chia-Chi** [comment]
Yes, it's slow because I use a relatively "heavy" backbone ResNet instead of VGG in original paper.
FPS is based on GPU and I can't recall the exact value. It's actually a project in college course so I do not have machine to check.
There are several ways to speed it up, retrain or distill a smaller net, change backbone or even compress bits...etc.
You could find official implementation in https://nol.cs.nctu.edu.tw:234/open-source/TrackNetv2.

**Comment by Q2Learn** [comment]
Do you know what the FPS is of the original paper with VGG? I don't see them mentioning it.

**Comment by Chang-Chia-Chi** [comment]
I have no idea, it didn't mention in the paper.
